# Generated by Django 6.0.1 on 2026-01-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='프로젝트 제목')),
                ('category', models.CharField(choices=[('GAME', '웹 게임'), ('COLAB', '구글 Colab'), ('GITHUB', 'GitHub 리포지토리'), ('OTHER', '기타 코드')], default='OTHER', max_length=20, verbose_name='유형')),
                ('url', models.URLField(verbose_name='공유 URL')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='MediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('file', models.FileField(upload_to='media_posts/', verbose_name='이미지/영상 파일')),
                ('ai_caption', models.TextField(blank=True, null=True, verbose_name='AI 분석 설명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='좋아요 수')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='사이트 이름')),
                ('icon_type', models.CharField(choices=[('YOUTUBE', '유튜브'), ('INSTAGRAM', '인스타그램'), ('BLOG', '블로그'), ('HOMEPAGE', '홈페이지')], max_length=20, verbose_name='아이콘 종류')),
                ('url', models.URLField(verbose_name='링크 주소')),
            ],
        ),
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문 내용')),
                ('author_name', models.CharField(max_length=50, verbose_name='작성자(학생명)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
