# Generated by Django 6.0.1 on 2026-02-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='media_posts/originals/', verbose_name='원본 파일 (관리자 전용)'),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='file',
            field=models.FileField(upload_to='media_posts/', verbose_name='이미지/영상 파일 (카툰 필터 적용됨)'),
        ),
    ]
