# Generated by Django 6.0.1 on 2026-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_mediapost_original_file_alter_mediapost_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='apply_webtoon_filter',
            field=models.BooleanField(default=False, verbose_name='웹툰체로 변환'),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='file',
            field=models.FileField(upload_to='media_posts/', verbose_name='이미지/영상 파일 (애니메이션 스타일)'),
        ),
    ]
