# Generated by Django 6.0.1 on 2026-03-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_mediapost_apply_webtoon_filter_alter_mediapost_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapost',
            name='ai_caption',
        ),
    ]
